# Generated by Django 2.2.1 on 2023-11-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_customer_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
