# Generated by Django 2.2.1 on 2023-11-20 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicles',
            new_name='cars',
        ),
    ]
