# Generated by Django 2.2.1 on 2023-11-21 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_auto_20231120_1151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='userlogin',
        ),
    ]
