# Generated by Django 2.2.1 on 2023-11-22 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_auto_20231121_1649'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userlogin',
            new_name='login',
        ),
    ]
