# Generated by Django 2.2.1 on 2023-11-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0007_auto_20231122_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcustomer',
            name='email_id',
            field=models.EmailField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='adddriver',
            name='aadhar_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
