# Generated by Django 2.2.1 on 2023-11-22 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0008_auto_20231122_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='username',
            new_name='Username',
        ),
    ]
