# Generated by Django 2.2.1 on 2023-11-22 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0009_auto_20231123_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='password',
            new_name='Password',
        ),
    ]
