# Generated by Django 2.2.1 on 2023-11-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0010_auto_20231123_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=200, null=True)),
                ('mobileno', models.CharField(blank=True, max_length=20, null=True)),
                ('emailid', models.EmailField(blank=True, max_length=500, null=True)),
                ('Password', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
