# Generated by Django 2.2.1 on 2023-11-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0011_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='utype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
