# Generated by Django 2.2.1 on 2023-11-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0012_register_utype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City_Airport_Station_etc', models.CharField(blank=True, max_length=200, null=True)),
                ('City_Airport_Station', models.CharField(blank=True, max_length=200, null=True)),
                ('book_pick_date', models.CharField(blank=True, max_length=200, null=True)),
                ('book_off_date', models.DateField(blank=True, null=True)),
                ('Time', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
