# Generated by Django 2.2.1 on 2023-11-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0013_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
