# Generated by Django 2.2.1 on 2023-11-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0014_auto_20231126_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='photo',
            field=models.FileField(upload_to='documents/static/images'),
        ),
    ]
