# Generated by Django 2.2.1 on 2023-11-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0019_auto_20231126_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='photo',
            field=models.FileField(upload_to='static/images'),
        ),
    ]
