# Generated by Django 2.2.1 on 2023-11-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0021_auto_20231126_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='photo',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
