# Generated by Django 2.2.1 on 2023-11-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0023_auto_20231126_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='photo',
            field=models.ImageField(upload_to='sem5/carrent/static/images/'),
        ),
    ]
