# Generated by Django 2.2.1 on 2023-11-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0025_auto_20231126_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/images/', verbose_name='Afbeelding'),
        ),
    ]
