# Generated by Django 2.2.1 on 2024-02-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0026_auto_20231126_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='photo',
            field=models.ImageField(blank=True, upload_to='owner/static/images/', verbose_name='Afbeelding'),
        ),
    ]
